# Vendored from OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550
# branch oneplus/sm8550_v_15.0.0_oneplus11, path vendor/oplus/kernel/cpu/waker_identify/Makefile.
# Verbatim.
LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_OPLUS_FEATURE_WAKER_IDENTIFY) += oplus_bsp_waker_identify.o
oplus_bsp_waker_identify-y := waker_identify.o
