# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2030 Oplus. All rights reserved.
# Vendored from OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8850
# branch oneplus/sm8850_b_16.0.0_oneplus_15, path
# vendor/oplus/kernel/storage/storage_feature_in_module/common/oplus_uprobe/.
# Adapted: GCOV_PROFILE dropped (needs CONFIG_GCOV_KERNEL, off here - would
# fail the link with undefined __gcov_*). Object list otherwise verbatim.

LINUXINCLUDE += -I$(srctree)/
obj-$(CONFIG_OPLUS_FEATURE_OPLUS_UPROBE) += oplus_uprobe.o
