# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2023-2025 Oplus. All rights reserved.
# Vendored from OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550
# branch oneplus/sm8550_v_15.0.0_oneplus11, path vendor/oplus/kernel/mm/kswapd_opt/Makefile.
# Verbatim.

LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_OPLUS_FEATURE_KSWAPD_OPT) += oplus_bsp_kswapd_opt.o

oplus_bsp_kswapd_opt-y := kswapd_opt.o
