# SPDX-License-Identifier: GPL-2.0-only
# Vendored from OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8850
# branch oneplus/sm8850_b_16.0.0_oneplus_15, path
# vendor/oplus/kernel/storage/storage_feature_in_module/common/storage_log/Makefile.
# Adapted: GCOV_PROFILE dropped (needs CONFIG_GCOV_KERNEL, off here).

LINUXINCLUDE += -I$(srctree)/
obj-$(CONFIG_OPLUS_FEATURE_STORAGE_LOG) += oplus_storage_log.o
oplus_storage_log-y := storage_log.o
