# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2023-2030 Oplus. All rights reserved.
# Vendored from OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8850
# branch oneplus/sm8850_b_16.0.0_oneplus_15, path vendor/oplus/kernel/patch/Makefile.
# In-tree part verbatim (the Kbuild file next to it is an out-of-tree stub
# and is intentionally not vendored).

obj-$(CONFIG_OPLUS_PATCH)          += oplus_patch.o
